function zipCode() {
  const min = 10000;
  const max = 99999;
  return Math.floor(Math.random() * (max - min + 1)) + min;
}
module.exports = {
  addresses: {
    moroccanAddresses: {
      cities: [
        'Casablanca', 
        'Rabat', 
        'Marrakech', 
        'Fes', 
        'Agadir', 
        'Tangier', 
        'Meknes', 
        'Oujda', 
        'Kenitra', 
        'Tetouan', 
        'Safi', 
        'Mohammedia', 
        'Khouribga', 
        'El Jadida', 
        'Beni Mellal', 
        'Nador', 
        'Taza', 
        'Settat', 
        'Berrechid', 
        'Ouarzazate', 
        'Berkane', 
        'Taourirt', 
        'Khemisset', 
        'Tiznit', 
        'Inezgane', 
        'Khenifra', 
        'Skhirat', 
        'Larache', 
        'Guelmim', 
        'Ksar El Kebir', 
        'Sidi Slimane', 
        'Errachidia', 
        'Essaouira', 
        'Al Hoceima', 
        'Oued Zem', 
        'Tifelt', 
        'Louda', 
        'Tiznit', 
        'Tan-Tan', 
        'Sidi Kacem', 
        'Taroudant', 
        'Tinghir', 
        'Oulad Teima', 
        'Sefrou', 
        'Berrechid', 
        'Chefchaouen', 
        'Dakhla', 
        'Bouskoura', 
        'Fquih Ben Salah', 
        'Benslimane', 
        'Martil', 
        'Youssoufia', 
        'Khouribga', 
        'Midelt', 
        'Sidi Bennour', 
        'Jerada', 
        'Fkih Ben Saleh', 
        'Tiflet', 
        'Souk Larbaa', 
        'Ben Guerir', 
        'Ouezzane', 
        'Beni Ansar', 
        'Taounate', 
        'Sidi Yahya El Gharb', 
        'Imzouren', 
        'Ksar El Kebir', 
        "M'diq", 
        'Sidi Ifni', 
        'Ahfir', 
        'Asilah', 
        'Tafraout', 
        'Berkane', 
        'Fnideq', 
        'Moulay Bousselham', 
        'Taliouine', 
        'Sidi Bennour', 
        'Mehdia', 
        'Lakhsas', 
        "M'Rirt", 
        'Oued Laou', 
        'Oulad Berhil', 
        'Sidi Allal Tazi', 
        'Ouazzane', 
        'Bouznika', 
        'Sidi Bou Othmane', 
        'Sidi Bennour', 
        'Ben Ahmed', 
        'Tidjikja', 
        'Ouad Zem', 
        'Ouaouizeght', 
        'Bir Gandouz'
      ],
      regions: [
        "Casablanca-Settat",
        "Rabat-Sale-Kenitra",
        "Marrakech-Safi",
        "Fes-Meknes",
        "Tanger-Tetouan-Al Hoceïma",
        "Souss-Massa",
        "Meknes-Tafilalet",
        "Oriental",
        "Beni Mellal-Khenifra",
        "Rabat-Sale-Kenitra",
      ],
      postalCodes: zipCode
    },
    usAddresses: {
      cities: [
        "New York",
        "Los Angeles",
        "Chicago",
        "Houston",
        "Miami",
        "San Francisco",
        "Boston",
        "Seattle",
        "Atlanta",
        "Dallas",
      ],
      states: [
        "New York",
        "California",
        "Illinois",
        "Texas",
        "Florida",
        "California",
        "Massachusetts",
        "Washington",
        "Georgia",
        "Texas",
      ],
      zipCodes: zipCode
    },
    frenchAddresses: {
      cities: [
        "Paris",
        "Marseille",
        "Lyon",
        "Toulouse",
        "Nice",
        "Nantes",
        "Strasbourg",
        "Montpellier",
        "Bordeaux",
        "Lille",
      ],
      regions: [
        "Île-de-France",
        "Provence-Alpes-Côte d'Azur",
        "Auvergne-Rhône-Alpes",
        "Occitanie",
        "Provence-Alpes-Côte d'Azur",
        "Pays de la Loire",
        "Grand Est",
        "Occitanie",
        "Nouvelle-Aquitaine",
        "Hauts-de-France",
      ],
      postalCodes: zipCode
    },
  },
};
