module.exports = {
  food: {
    foodNames: [
      "Pizza",
      "Burger",
      "Sushi",
      "Pasta",
      "Taco",
      "Salad",
      "Ice Cream",
      "Steak",
      "Chicken Curry",
      "Mashed Potatoes",
    ],
    cuisines: [
      "Italian",
      "American",
      "Japanese",
      "Italian",
      "Mexican",
      "Various",
      "Dessert",
      "Steakhouse",
      "Indian",
      "American",
    ],
    ingredients: [
      ["Dough", "Tomato Sauce", "Cheese", "Pepperoni"],
      ["Bun", "Beef Patty", "Lettuce", "Tomato", "Cheese"],
      ["Rice", "Raw Fish", "Seaweed", "Vegetables"],
      ["Pasta", "Tomato Sauce", "Parmesan Cheese"],
      ["Tortilla", "Seasoned Meat", "Lettuce", "Tomato", "Salsa"],
      ["Greens", "Tomatoes", "Cucumbers", "Dressing"],
      ["Milk", "Cream", "Sugar", "Flavoring"],
      ["Steak", "Salt", "Pepper", "Butter"],
      ["Chicken", "Curry Sauce", "Spices", "Rice"],
      ["Potatoes", "Butter", "Milk", "Salt"],
    ],
  },
};
