module.exports = {
  holidays: {
    holidayNames: [
      "Christmas",
      "New Year's Day",
      "Thanksgiving",
      "Easter",
      "Halloween",
      "Independence Day",
      "Valentine's Day",
      "Labor Day",
      "Memorial Day",
      "Hanukkah",
    ],
    holidayDates: [
      "2023-12-25",
      "2023-01-01",
      "2023-11-24",
      "2023-04-16",
      "2023-10-31",
      "2023-07-04",
      "2023-02-14",
      "2023-09-04",
      "2023-05-29",
      "2023-12-12",
    ],
    holidayDescriptions: [
      "Celebrating the birth of Jesus Christ.",
      "The first day of the new year.",
      "A day of gratitude and feasting.",
      "A religious holiday celebrating the resurrection of Jesus.",
      "A holiday for costumes and candies.",
      "Celebrating the nation's independence.",
      "A day to express love and affection.",
      "Honoring the contributions of workers.",
      "Remembering and honoring the military personnel who have died.",
      "An eight-day Jewish festival of lights.",
    ],
  },
};
