module.exports = {
    firstname: [
      "John",
      "Alice",
      "Bob",
      "Eva",
      "Michael",
      "Sophia",
      "Daniel",
      "Olivia",
      "Matthew",
      "Ava",
      "William",
      "Emma",
      "Alexander",
      "Isabella",
      "James",
      "Mia",
      "Benjamin",
      "Abigail",
      "David",
      "Emily",
      "Joseph",
      "Charlotte",
      "Christopher",
      "Amelia",
      "Andrew",
      "Harper",
      "Nathan",
      "Evelyn",
      "Samuel",
      "Ella",
      "Nicholas",
      "Grace",
      "Jacob",
      "Avery",
      "Logan",
      "Scarlett",
      "Ryan",
      "Chloe",
      "Christian",
      "Victoria",
      "Gabriel",
      "Aria",
      "Jonathan",
      "Liam",
      "Lillian",
      "Anthony",
      "Madison",
      "Dylan",
      "Sofia",
      "Brandon",
      "Addison",
      "Caleb",
      "Aubrey",
      "Ethan",
      "Layla",
      "Isaac",
      "Hannah",
      "Owen",
      "Natalie",
      "Luke",
      "Zoe",
      "Isaiah",
      "Brooklyn",
      "Henry",
      "Audrey",
      "Jackson",
      "Leah",
      "Wyatt",
      "Stella",
      "Elijah",
      "Peyton",
      "Julian",
      "Nora",
      "Cameron",
      "Lucy",
      "Isabel",
      "Austin",
      "Ellie",
      "Leo",
      "Claire",
      "Hunter",
      "Skylar",
      "Adam",
      "Maya",
      "Jayden",
      "Anna",
      "Evan",
      "Lily",
      "Mason",
      "Katherine",
      "Jack",
      "Bella",
      "Carter",
      "Aaliyah",
      "Jaden",
      "Gabriella",
      "Tyler",
      "Alexa",
      "Eli",
      "Ariana",
      "Nathaniel",
      "Mila",
      "Sebastian",
      "Paisley",
      "Colton",
      "Hazel",
      "Kevin",
      "Kylie",
      "Zachary",
      "Ellie",
      "Xavier",
      "Taylor",
      "Cooper",
      "Kaylee",
      "Levi",
      "Luna",
      "Carson",
      "Lydia",
      "Brayden",
      "Gianna",
      "Dominic",
      "Liliana",
      "Josiah",
      "Aubree",
      "Vincent",
      "Savannah",
      "Parker",
      "Zara",
      "Johnathan",
      "Aurora",
      "Chase",
      "Holly",
      "Roman",
      "Brianna",
      "Alex",
      "Penelope",
      "Jason",
      "Allison",
      "Aaron",
      "Layla",
      "Charles",
      "Alyssa",
      "Grayson",
      "Violet",
      "Colin",
      "Ruby",
      "Ezra",
      "Clara",
      "Thomas",
      "Samantha",
      "Jace",
      "Elena",
      "Xander",
      "Alexis",
      "Landon",
      "Nevaeh",
      "Adrian",
      "Gabrielle",
      "Connor",
      "Mackenzie",
      "Jordan",
      "Sadie",
      "Leighton",
      "Riley",
      "Xavi",
      "Piper",
      "Oscar",
      "Delilah",
      "Finn",
      "Aubrey",
      "Miles",
      "Ariel",
      "Silas",
      "Emma",
      // ... Add more names as needed
    ],
    lastname: [
      "Smith",
      "Johnson",
      "Williams",
      "Jones",
      "Brown",
      "Davis",
      "Miller",
      "Wilson",
      "Moore",
      "Taylor",
      "Anderson",
      "Thomas",
      "Jackson",
      "White",
      "Harris",
      "Martin",
      "Thompson",
      "Garcia",
      "Martinez",
      "Robinson",
      "Clark",
      "Rodriguez",
      "Lewis",
      "Lee",
      "Walker",
      "Hall",
      "Allen",
      "Young",
      "Hernandez",
      "King",
      "Wright",
      "Lopez",
      "Hill",
      "Scott",
      "Green",
      "Adams",
      "Baker",
      "Gonzalez",
      "Nelson",
      "Carter",
      "Mitchell",
      "Perez",
      "Roberts",
      "Turner",
      "Phillips",
      "Campbell",
      "Parker",
      "Evans",
      "Edwards",
      "Collins",
      "Stewart",
      "Sanchez",
      "Morris",
      "Rogers",
      "Reed",
      "Cook",
      "Morgan",
      "Bell",
      "Murphy",
      "Bailey",
      "Rivera",
      "Cooper",
      "Richardson",
      "Cox",
      "Howard",
      "Ward",
      "Torres",
      "Peterson",
      "Gray",
      "Ramirez",
      "James",
      "Watson",
      "Brooks",
      "Kelly",
      "Sanders",
      "Price",
      "Bennett",
      "Wood",
      "Barnes",
      "Ross",
      "Henderson",
      "Coleman",
      "Jenkins",
      "Perry",
      "Powell",
      "Long",
      "Patterson",
      "Hughes",
      "Flores",
      "Washington",
      "Butler",
      "Simmons",
      "Foster",
      "Gonzales",
      "Bryant",
      "Alexander",
      "Russell",
      "Griffin",
      "Diaz",
      "Hayes",
      "Myers",
      "Ford",
      "Hamilton",
      "Graham",
      "Sullivan",
      "Wallace",
      "Woods",
      "Cole",
      "West",
      "Jordan",
      "Owens",
      "Reynolds",
      "Fisher",
      "Ellis",
      "Harrison",
      "Gibson",
      "Mcdonald",
      "Cruz",
      "Marshall",
      "Ortiz",
      "Gomez",
      "Murray",
      "Freeman",
      "Wells",
      "Webb",
      "Simpson",
      "Stevens",
      "Tucker",
      "Porter",
      "Hunter",
      "Hicks",
      "Crawford",
      "Henry",
      "Boyd",
      "Mason",
      "Morales",
      "Kennedy",
      "Warren",
      "Dixon",
      "Ramos",
      "Reyes",
      "Burns",
      "Gordon",
      "Shaw",
      "Holmes",
      "Rice",
      "Robertson",
      "Hunt",
      "Black",
      "Daniels",
      "Palmer",
      "Mills",
      "Nichols",
      "Grant",
      "Knight",
      "Ferguson",
      "Rose",
      "Stone",
      "Hawkins",
      "Dunn",
    ],
    username: ['johndoe', 'sarahsmith', 'michaelj', 'emma.d', 'davidwilson'],
    email: ['john@example.com', 'sarah@example.com', 'michael@example.com', 'emma@example.com', 'david@example.com'],
    password: ['password1', 'password2', 'password3', 'password4', 'password5'],
    age: [30, 25, 35, 28, 40],
    phone: ['123-456-7890', '987-654-3210', '555-123-4567', '888-777-5555', '444-333-2222'],
    address: ['123 Main St', '456 Elm St', '789 Oak St', '321 Pine St', '555 Cedar St'],
    job: [
      "Software Engineer",
      "Data Scientist",
      "Graphic Designer",
      "Marketing Specialist",
      "Financial Analyst",
      "Human Resources Manager",
      "Product Manager",
      "Customer Support Representative",
      "Sales Manager",
      "Business Analyst",
      "Content Writer",
      "UX/UI Designer",
      "Project Manager",
      "Systems Administrator",
      "Network Engineer",
      "Social Media Manager",
      "Digital Marketing Manager",
      "Accountant",
      "Operations Manager",
      "IT Consultant",
      "Web Developer",
      "Quality Assurance Analyst",
      "Research Analyst",
      "Legal Counsel",
      "Logistics Coordinator",
      "Event Planner",
      "Executive Assistant",
      "Public Relations Specialist",
      "Healthcare Administrator",
      "Teacher",
      "Nurse",
      "Architect",
      "Mechanical Engineer",
      "Electrician",
      "Plumber",
      "Construction Project Manager",
      "Chef",
      "Barista",
      "Fitness Trainer",
      "Interior Designer",
      "Photographer",
      "Police Officer",
      "Firefighter",
      "Paramedic",
      "Pilot",
      "Flight Attendant",
      "Journalist",
      "Librarian",
      "Real Estate Agent",
      "Social Worker",
      "Psychologist",
      "Counselor",
      "Pharmacist",
      "Veterinarian",
      "Biomedical Scientist",
      "Environmental Engineer",
      "Research Scientist",
      "Biotech Analyst",
      "Geologist",
      "Meteorologist",
      "Astronomer",
      "Fashion Designer",
      "Retail Manager",
      "Stock Trader",
      "Actuary",
      "Translator",
      "Electrician",
      "IT Support Specialist",
      "Cryptocurrency Analyst",
      "Blockchain Developer",
      "Ethical Hacker",
      "GIS Specialist",
      "Solar Energy Consultant",
      "Marine Biologist",
      "Robotics Engineer",
      "Virtual Reality Developer",
      "Dental Hygienist",
      "Phlebotomist",
      "Fitness Instructor",
      "Social Media Influencer",
      "Podcast Producer",
      "Gaming Developer",
      "Forensic Scientist",
      "Ethnobotanist",
      "Zoologist",
      "Neuroscientist",
      "Biomedical Engineer",
      "Epidemiologist",
      "Medical Illustrator",
      "Forestry Technician",
      "Sustainability Consultant",
      "Bioinformatician",
      "Machine Learning Engineer",
    ],
    status: ()=>{
      //returns true or false
      let status= Math.random() < 0.5 ?'Active': "Inactive" ;
      return status;
    },
    avatar: ['avatar1.jpg', 'avatar2.jpg', 'avatar3.jpg', 'avatar4.jpg', 'avatar5.jpg']
  };