module.exports = {
  produits: {
    noms: [
      "Blue T-shirt",
      "Coffee Mug",
      "Notebook",
      "Wireless Mouse",
      "Sunglasses",
      "Laptop Stand",
      "Canvas Backpack",
      "Stainless Steel Water Bottle",
      "Desk Organizer",
      "Cotton Socks",
      "Running Shoes",
      "Phone Holder",
      "Smartphone Case",
      "USB Flash Drive",
      "Whiteboard Markers",
      "Desk Lamp",
      "Pocket Umbrella",
      "Leather Wallet",
      "Travel Pillow",
      "Insulated Lunch Box",
      "Stainless Steel Travel Mug",
      "Yoga Mat",
      "Resistance Bands",
      "Bluetooth Earphones",
      "Wireless Charger",
      "Portable Speaker",
      "Beach Towel",
      "Graphic Novel",
      "Ceramic Plant Pot",
      "Puzzle Game",
      "Crossbody Bag",
      "Sleep Mask",
      "Aromatherapy Diffuser",
      "Fitness Tracker",
      "Dumbbell Set",
      "Camping Lantern",
      "Reusable Grocery Bags",
      "Hair Dryer",
      "Facial Cleanser",
      "Cooking Utensil Set",
      "Bike Lock",
      "Spiral-bound Sketchbook",
      "Sports Water Bottle",
      "Jigsaw Puzzle",
      "Reusable Silicone Food Bags",
      "Portable Fan",
      "Travel Adapter",
      "Hiking Boots",
      "Foldable Camping Chair",
      "Coloring Book",
      "Power Bank",
      "Microfiber Towel",
      "Pedometer",
      "Screen Protector",
      "Foldable Bluetooth Keyboard",
      "Camping Cookware Set",
      "Sleeping Bag",
      "Hand Sanitizer",
      "Sunscreen",
      "Reading Glasses",
      "Plastic Hangers",
      "Adjustable Wrench",
      "Rain Poncho",
      "Insulated Wine Tumbler",
      "Car Phone Mount",
      "Stainless Steel Straw Set",
      "Wooden Clothespins",
      "Shower Caddy",
      "Magnetic Whiteboard",
      "Reusable Coffee Filter",
      "LED Flashlight",
      "Colorful Markers",
      "Travel Toiletry Kit",
      "Kettlebell",
      "Rolling Duffel Bag",
      "Outdoor Blanket",
      "Tea Infuser",
      "Portable Ice Maker",
      "Smart Home Plug",
      "Vegetable Spiralizer",
      "Ceramic Coasters",
      "Digital Meat Thermometer",
      "Yoga Block",
      "Collapsible Water Bowl",
      "Carabiner Clip",
      "Puzzle Mat",
      "Luggage Scale",
      "Camping Hammock",
      "Foldable Sun Hat",
      "Bamboo Toothbrush Set",
      "Hiking Pole",
      "Hand Warmer",
      "Bluetooth FM Transmitter",
      "Portable Charcoal Grill",
      "Waterproof Dry Bag",
      "Silicone Baking Mat",
      "Travel Laundry Bag",
      "Rechargeable Hand Warmer",
      "Collapsible Water Bottle",
      "Inflatable Neck Pillow",
      "Car Trash Can",
      "Portable Espresso Maker",
      "Cord Organizer",
      "Reusable Stainless Steel Straw",
      "Camping Stove",
      "Silicone Food Storage Bags",
      "Fitness Dice",
      "LED Book Light",
      "Stainless Steel Mixing Bowls",
      "Glow-in-the-dark Stars Stickers",
      "Portable BBQ Grill",
      "Travel Neck Wallet",
      "Multi-Tool",
      "Camping Tent",
      "Adjustable Laptop Stand",
      "Puzzle Cube",
      "Magnetic Cable Organizer",
      "Sleeping Mask with Earplugs",
      "Resistance Loop Bands",
      "Collapsible Food Container",
      "Camping Cot",
      "Mini First Aid Kit",
      "Camping Headlamp",
      "Retractable Clothesline",
      "Foam Roller",
      "Foldable Solar Charger",
      "Reusable Beeswax Wraps",
      "Camping Coffee Maker",
      "Bike Repair Kit",
      "Pocket Multi-Tool",
      "Outdoor Portable Table",
      "Basic T-Shirt",
      "Cotton Socks",
      "Stainless Steel Water Bottle",
      "Wooden Desk Organizer",
      "LED Desk Lamp",
      "Notebook Set",
      "Canvas Backpack",
      "Wireless Mouse",
      "Coffee Mug",
      "Pocket Umbrella",
      "Bluetooth Earphones",
      "Portable Power Bank",
      "Glass Water Pitcher",
      "Non-Stick Frying Pan",
      "Yoga Mat",
      "Travel Pillow",
      "Leather Wallet",
      "Sunglasses",
      "Desk Chair",
      "Ceramic Plant Pot",
      "Hiking Backpack",
      "Digital Alarm Clock",
      "Stainless Steel Travel Mug",
      "Fitness Tracker",
      "USB Flash Drive",
      "Smartphone Stand",
      "Reusable Shopping Bag",
      "Stainless Steel Cutlery Set",
      "Gaming Mousepad",
      "Hair Dryer",
      "Cotton Pillowcase Set",
      "Resistance Bands Set",
      "Kitchen Timer",
      "Wall Clock",
      "Bamboo Toothbrush Set",
      "Garden Gloves",
      "HDMI Cable",
      "Cooking Apron",
      "Laptop Stand",
      "Running Shoes",
      "Microfiber Cleaning Cloths",
      "Insulated Lunch Box",
      "Cotton Towel Set",
      "Bluetooth Speaker",
      "Running Belt",
      "Sleeping Mask",
      "Silicone Baking Mat",
      "Wireless Charger",
      "Stainless Steel Mixing Bowls",
      "Tea Infuser",
      "Elastic Shoe Laces",
      "Handheld Fan",
      "Reusable Ice Cubes",
      "Sunscreen Lotion",
      "Foldable Backpack",
      "Bike Water Bottle Holder",
      "Fitness Foam Roller",
      "Gel Ink Pens Set",
      "Car Phone Holder",
      "Hand Sanitizer Gel",
      "Gourmet Coffee Beans",
      "Adjustable Laptop Desk",
      "Desk Organizer Set",
      "Stainless Steel Straw Set",
      "LED String Lights",
      "Faux Leather Journal",
      "Electric Kettle",
      "Bicycle Repair Tool Kit",
      "Portable Bluetooth Keyboard",
      "Soy Wax Candles Set",
      "Metallic Watercolor Paint Set",
      "Hiking Trail Mix",
      "Puzzle Board Game",
      "Hydration Backpack",
      "Non-Slip Yoga Mat",
      "Resistance Loop Bands",
      "USB-C Hub",
      "Artificial Succulent Plants",
      "Glass Spice Jars Set",
      "Reusable Silicone Food Storage Bags",
      "Inflatable Travel Neck Pillow",
      "Camping Cookware Set",
      "Cotton Oven Mitts",
      "Collapsible Water Bottle",
      "Silicone Food Huggers Set",
      "Portable Espresso Maker",
      "Miniature Desk Plant",
      "Wooden Clothes Hangers Set",
      "Aromatherapy Essential Oils Set",
      "Foldable Laundry Basket",
      "Insulated Wine Tumbler",
      "Ceramic Coasters Set",
      "USB Desk Fan",
      "Cotton Face Masks Set",
    ],
    descriptions: ['Description A', 'Description B', 'Description C', 'Description D', 'Description E'],
    prix: ()=>{
      max= 10000;
      min=10;
      const randomPrice = (Math.random() * (max - min + 1)) + min;
      const formattedPrice = randomPrice.toFixed(2)
      return formattedPrice
    },
    catégories: ['Électronique', 'Vêtements', 'Maison et Jardin', 'Jouets', 'Livres'],
    images: ['produitA.jpg', 'produitB.jpg', 'produitC.jpg', 'produitD.jpg', 'produitE.jpg'],
    disponibilité: ()=>{
      //returns true or false
      return Math.random() < 0.5;
    },
  },
};
