module.exports = {
  addresses: {
    moroccanAddresses: {
      cities: [
        "Casablanca",
        "Rabat",
        "Marrakech",
        "Fès",
        "Tanger",
        "Agadir",
        "Meknès",
        "Oujda",
        "Fez",
        "Kenitra",
      ],
      regions: [
        "Casablanca-Settat",
        "Rabat-Salé-Kénitra",
        "Marrakech-Safi",
        "Fès-Meknès",
        "Tanger-Tétouan-Al Hoceïma",
        "Souss-Massa",
        "Meknès-Tafilalet",
        "Oriental",
        "Béni Mellal-Khénifra",
        "Rabat-Salé-Kénitra",
      ],
      postalCodes: [
        "20000",
        "10000",
        "40000",
        "30000",
        "90000",
        "80000",
        "50000",
        "60000",
        "35000",
        "12000",
      ],
    },
    usAddresses: {
      cities: [
        "New York",
        "Los Angeles",
        "Chicago",
        "Houston",
        "Miami",
        "San Francisco",
        "Boston",
        "Seattle",
        "Atlanta",
        "Dallas",
      ],
      states: [
        "New York",
        "California",
        "Illinois",
        "Texas",
        "Florida",
        "California",
        "Massachusetts",
        "Washington",
        "Georgia",
        "Texas",
      ],
      zipCodes: [
        "10001",
        "90001",
        "60601",
        "77001",
        "33101",
        "94101",
        "02101",
        "98101",
        "30301",
        "75201",
      ],
    },
    frenchAddresses: {
      cities: [
        "Paris",
        "Marseille",
        "Lyon",
        "Toulouse",
        "Nice",
        "Nantes",
        "Strasbourg",
        "Montpellier",
        "Bordeaux",
        "Lille",
      ],
      regions: [
        "Île-de-France",
        "Provence-Alpes-Côte d'Azur",
        "Auvergne-Rhône-Alpes",
        "Occitanie",
        "Provence-Alpes-Côte d'Azur",
        "Pays de la Loire",
        "Grand Est",
        "Occitanie",
        "Nouvelle-Aquitaine",
        "Hauts-de-France",
      ],
      postalCodes: [
        "75000",
        "13000",
        "69000",
        "31000",
        "06000",
        "44000",
        "67000",
        "34000",
        "33000",
        "59000",
      ],
    },
  },
};
