module.exports = {
  food: {
    foodNames: [
      "Pizza",
      "Burger",
      "Sushi",
      "Pâtes",
      "Taco",
      "Salade",
      "Glace",
      "Steak",
      "Curry de Poulet",
      "Purée de Pommes de Terre",
    ],
    cuisines: [
      "Italienne",
      "Américaine",
      "Japonaise",
      "Italienne",
      "Mexicaine",
      "Diverses",
      "Dessert",
      "Steakhouse",
      "Indienne",
      "Américaine",
    ],
    ingredients: [
      ["Pâte", "Sauce Tomate", "Fromage", "Pepperoni"],
      ["Bun", "Steak Haché", "Laitue", "Tomate", "Fromage"],
      ["Riz", "Poisson Cru", "Algues", "Légumes"],
      ["Pâtes", "Sauce Tomate", "Fromage Parmesan"],
      ["Tortilla", "Viande Assaisonnée", "Laitue", "Tomate", "Salsa"],
      ["Légumes Verts", "Tomates", "Concombres", "Assaisonnement"],
      ["Lait", "Crème", "Sucre", "Arôme"],
      ["Steak", "Sel", "Poivre", "Beurre"],
      ["Poulet", "Sauce Curry", "Épices", "Riz"],
      ["Pommes de Terre", "Beurre", "Lait", "Sel"],
    ],
  },
};
