module.exports = {
  holidays: {
    holidayNames: [
      "Noël",
      "Jour de l'An",
      "Action de grâce",
      "Pâques",
      "Halloween",
      "Jour de l'Indépendance",
      "Saint-Valentin",
      "Fête du Travail",
      "Jour du Souvenir",
      "Hanukkah",
    ],
    holidayDates: [
      "2023-12-25",
      "2023-01-01",
      "2023-11-24",
      "2023-04-16",
      "2023-10-31",
      "2023-07-04",
      "2023-02-14",
      "2023-09-04",
      "2023-05-29",
      "2023-12-12",
    ],
    holidayDescriptions: [
      "Célébration de la naissance de Jésus-Christ.",
      "Le premier jour de la nouvelle année.",
      "Un jour de gratitude et de festivités.",
      "Une fête religieuse célébrant la résurrection de Jésus.",
      "Une fête déguisée avec des bonbons.",
      "Célébration de l'indépendance nationale.",
      "Un jour pour exprimer l'amour et l'affection.",
      "Honneur aux contributions des travailleurs.",
      "Commémoration et hommage aux militaires décédés.",
      "Une fête juive de huit jours des lumières.",
    ],
  },
};
