module.exports = {
    firstname:  [
        "John",
        "Alice",
        "Bob",
        "Eva",
        "Michael",
        "Sophia",
        "Daniel",
        "Olivia",
        "Matthew",
        "Ava",
        "William",
        "Emma",
        "Alexander",
        "Isabella",
        "James",
        "Mia",
        "Benjamin",
        "Abigail",
        "David",
        "Emily",
        "Joseph",
        "Charlotte",
        "Christopher",
        "Amelia",
        "Andrew",
        "Harper",
        "Nathan",
        "Evelyn",
        "Samuel",
        "Ella",
        "Nicholas",
        "Grace",
        "Jacob",
        "Avery",
        "Logan",
        "Scarlett",
        "Ryan",
        "Chloe",
        "Christian",
        "Victoria",
        "Gabriel",
        "Aria",
        "Jonathan",
        "Liam",
        "Lillian",
        "Anthony",
        "Madison",
        "Dylan",
        "Sofia",
        "Brandon",
        "Addison",
        "Caleb",
        "Aubrey",
        "Ethan",
        "Layla",
        "Isaac",
        "Hannah",
        "Owen",
        "Natalie",
        "Luke",
        "Zoe",
        "Isaiah",
        "Brooklyn",
        "Henry",
        "Audrey",
        "Jackson",
        "Leah",
        "Wyatt",
        "Stella",
        "Elijah",
        "Peyton",
        "Julian",
        "Nora",
        "Cameron",
        "Lucy",
        "Isabel",
        "Austin",
        "Ellie",
        "Leo",
        "Claire",
        "Hunter",
        "Skylar",
        "Adam",
        "Maya",
        "Jayden",
        "Anna",
        "Evan",
        "Lily",
        "Mason",
        "Katherine",
        "Jack",
        "Bella",
        "Carter",
        "Aaliyah",
        "Jaden",
        "Gabriella",
        "Tyler",
        "Alexa",
        "Eli",
        "Ariana",
        "Nathaniel",
        "Mila",
        "Sebastian",
        "Paisley",
        "Colton",
        "Hazel",
        "Kevin",
        "Kylie",
        "Zachary",
        "Ellie",
        "Xavier",
        "Taylor",
        "Cooper",
        "Kaylee",
        "Levi",
        "Luna",
        "Carson",
        "Lydia",
        "Brayden",
        "Gianna",
        "Dominic",
        "Liliana",
        "Josiah",
        "Aubree",
        "Vincent",
        "Savannah",
        "Parker",
        "Zara",
        "Johnathan",
        "Aurora",
        "Chase",
        "Holly",
        "Roman",
        "Brianna",
        "Alex",
        "Penelope",
        "Jason",
        "Allison",
        "Aaron",
        "Layla",
        "Charles",
        "Alyssa",
        "Grayson",
        "Violet",
        "Colin",
        "Ruby",
        "Ezra",
        "Clara",
        "Thomas",
        "Samantha",
        "Jace",
        "Elena",
        "Xander",
        "Alexis",
        "Landon",
        "Nevaeh",
        "Adrian",
        "Gabrielle",
        "Connor",
        "Mackenzie",
        "Jordan",
        "Sadie",
        "Leighton",
        "Riley",
        "Xavi",
        "Piper",
        "Oscar",
        "Delilah",
        "Finn",
        "Aubrey",
        "Miles",
        "Ariel",
        "Silas",
        "Emma",
        // ... Add more names as needed
      ],
    lastname: [
        "Smith",
        "Johnson",
        "Williams",
        "Jones",
        "Brown",
        "Davis",
        "Miller",
        "Wilson",
        "Moore",
        "Taylor",
        "Anderson",
        "Thomas",
        "Jackson",
        "White",
        "Harris",
        "Martin",
        "Thompson",
        "Garcia",
        "Martinez",
        "Robinson",
        "Clark",
        "Rodriguez",
        "Lewis",
        "Lee",
        "Walker",
        "Hall",
        "Allen",
        "Young",
        "Hernandez",
        "King",
        "Wright",
        "Lopez",
        "Hill",
        "Scott",
        "Green",
        "Adams",
        "Baker",
        "Gonzalez",
        "Nelson",
        "Carter",
        "Mitchell",
        "Perez",
        "Roberts",
        "Turner",
        "Phillips",
        "Campbell",
        "Parker",
        "Evans",
        "Edwards",
        "Collins",
        "Stewart",
        "Sanchez",
        "Morris",
        "Rogers",
        "Reed",
        "Cook",
        "Morgan",
        "Bell",
        "Murphy",
        "Bailey",
        "Rivera",
        "Cooper",
        "Richardson",
        "Cox",
        "Howard",
        "Ward",
        "Torres",
        "Peterson",
        "Gray",
        "Ramirez",
        "James",
        "Watson",
        "Brooks",
        "Kelly",
        "Sanders",
        "Price",
        "Bennett",
        "Wood",
        "Barnes",
        "Ross",
        "Henderson",
        "Coleman",
        "Jenkins",
        "Perry",
        "Powell",
        "Long",
        "Patterson",
        "Hughes",
        "Flores",
        "Washington",
        "Butler",
        "Simmons",
        "Foster",
        "Gonzales",
        "Bryant",
        "Alexander",
        "Russell",
        "Griffin",
        "Diaz",
        "Hayes",
        "Myers",
        "Ford",
        "Hamilton",
        "Graham",
        "Sullivan",
        "Wallace",
        "Woods",
        "Cole",
        "West",
        "Jordan",
        "Owens",
        "Reynolds",
        "Fisher",
        "Ellis",
        "Harrison",
        "Gibson",
        "Mcdonald",
        "Cruz",
        "Marshall",
        "Ortiz",
        "Gomez",
        "Murray",
        "Freeman",
        "Wells",
        "Webb",
        "Simpson",
        "Stevens",
        "Tucker",
        "Porter",
        "Hunter",
        "Hicks",
        "Crawford",
        "Henry",
        "Boyd",
        "Mason",
        "Morales",
        "Kennedy",
        "Warren",
        "Dixon",
        "Ramos",
        "Reyes",
        "Burns",
        "Gordon",
        "Shaw",
        "Holmes",
        "Rice",
        "Robertson",
        "Hunt",
        "Black",
        "Daniels",
        "Palmer",
        "Mills",
        "Nichols",
        "Grant",
        "Knight",
        "Ferguson",
        "Rose",
        "Stone",
        "Hawkins",
        "Dunn",
      ],
    username: ['jean.dupont', 'sarah.dupont', 'michaelj', 'emma.d', 'david.dupont'],
    email: ['jean@example.com', 'sarah@example.com', 'michael@example.com', 'emma@example.com', 'david@example.com'],
    password: ['motdepasse1', 'motdepasse2', 'motdepasse3', 'motdepasse4', 'motdepasse5'],
    age: [30, 25, 35, 28, 40],
    phone: ['123-456-7890', '987-654-3210', '555-123-4567', '888-777-5555', '444-333-2222'],
    address: ['123 Rue Principale', '456 Rue du Frêne', '789 Rue des Chênes', '321 Rue des Pins', '555 Rue du Cèdre'],
    job: [
        "Ingénieur logiciel",
        "Data Scientist",
        "Designer graphique",
        "Spécialiste du marketing",
        "Analyste financier",
        "Responsable des ressources humaines",
        "Chef de produit",
        "Représentant du service client",
        "Directeur des ventes",
        "Analyste d'affaires",
        "Rédacteur de contenu",
        "Concepteur UX/UI",
        "Chef de projet",
        "Administrateur système",
        "Ingénieur réseau",
        "Gestionnaire des médias sociaux",
        "Responsable du marketing digital",
        "Comptable",
        "Directeur des opérations",
        "Consultant en informatique",
        "Développeur web",
        "Analyste en assurance qualité",
        "Analyste de recherche",
        "Conseiller juridique",
        "Coordinateur logistique",
        "Organisateur d'événements",
        "Assistant de direction",
        "Spécialiste des relations publiques",
        "Administrateur de la santé",
        "Enseignant",
        "Infirmier",
        "Architecte",
        "Ingénieur mécanique",
        "Électricien",
        "Plombier",
        "Chef de projet en construction",
        "Chef cuisinier",
        "Barista",
        "Entraîneur de fitness",
        "Designer d'intérieur",
        "Photographe",
        "Agent de police",
        "Pompier",
        "Ambulancier",
        "Pilote",
        "Agent de bord",
        "Journaliste",
        "Bibliothécaire",
        "Agent immobilier",
        "Travailleur social",
        "Psychologue",
        "Conseiller",
        "Pharmacien",
        "Vétérinaire",
        "Scientifique biomédical",
        "Ingénieur environnemental",
        "Chercheur scientifique",
        "Analyste en biotechnologie",
        "Géologue",
        "Météorologue",
        "Astronome",
        "Styliste",
        "Directeur de magasin",
        "Trader en bourse",
        "Actuaire",
        "Traducteur",
        "Électricien",
        "Spécialiste du support informatique",
        "Analyste en crypto-monnaie",
        "Développeur Blockchain",
        "Hacker éthique",
        "Spécialiste SIG",
        "Consultant en énergie solaire",
        "Biologiste marin",
        "Ingénieur en robotique",
        "Développeur de réalité virtuelle",
        "Hygiéniste dentaire",
        "Phlébotomiste",
        "Instructeur de fitness",
        "Influenceur des médias sociaux",
        "Producteur de podcast",
        "Développeur de jeux",
        "Scientifique médico-légal",
        "Ethnobotaniste",
        "Zoologiste",
        "Neuroscientifique",
        "Ingénieur biomédical",
        "Épidémiologiste",
        "Illustrateur médical",
        "Technicien forestier",
        "Consultant en durabilité",
        "Bioinformaticien",
        "Ingénieur en apprentissage automatique",
      ],
    status: ()=>{
      //returns true or false
      let status= Math.random() < 0.5 ?'Actif': "Inactif" ;
      return status;
    },
    avatar: ['avatar1.jpg', 'avatar2.jpg', 'avatar3.jpg', 'avatar4.jpg', 'avatar5.jpg']
};
