module.exports = {
  produits: {
    noms: [
      "T-shirt bleu",
      "Mug de café",
      "Carnet",
      "Souris sans fil",
      "Lunettes de soleil",
      "Support pour ordinateur portable",
      "Sac à dos en toile",
      "Bouteille d'eau en acier inoxydable",
      "Organisateur de bureau en bois",
      "Chaussettes en coton",
      "Chaussures de course",
      "Support de téléphone",
      "Coque de smartphone",
      "Clé USB",
      "Marqueurs pour tableau blanc",
      "Lampe de bureau",
      "Parapluie de poche",
      "Portefeuille en cuir",
      "Oreiller de voyage",
      "Boîte à lunch isolée",
      "Mug de voyage en acier inoxydable",
      "Tapis de yoga",
      "Bandes de résistance",
      "Écouteurs Bluetooth",
      "Chargeur sans fil",
      "Enceinte portable",
      "Serviette de plage",
      "Roman graphique",
      "Pot de fleur en céramique",
      "Jeu de puzzle",
      "Sac bandoulière",
      "Masque de sommeil",
      "Diffuseur d'aromathérapie",
      "Suivi de fitness",
      "Set d'haltères",
      "Lanterne de camping",
      "Sacs d'épicerie réutilisables",
      "Sèche-cheveux",
      "Nettoyant pour le visage",
      "Set d'ustensiles de cuisine",
      "Antivol pour vélo",
      "Carnet de croquis à spirale",
      "Bouteille d'eau de sport",
      "Puzzle",
      "Sacs de stockage alimentaire en silicone réutilisables",
      "Ventilateur portable",
      "Adaptateur de voyage",
      "Bottes de randonnée",
      "Chaise de camping pliante",
      "Livre de coloriage",
      "Batterie externe",
      "Serviette en microfibre",
      "Podomètre",
      "Protection d'écran",
      "Clavier Bluetooth pliable",
      "Set de cuisson de camping",
      "Sac de couchage",
      "Gel désinfectant pour les mains",
      "Crème solaire",
      "Lunettes de lecture",
      "Cintres en plastique",
      "Clé à molette réglable",
      "Poncho de pluie",
      "Gobelet à vin isolé",
      "Support de téléphone pour voiture",
      "Set de pailles en acier inoxydable",
      "Pinces à linge en bois",
      "Panier de douche",
      "Tableau blanc magnétique",
      "Filtre à café réutilisable",
      "Lampe de poche LED",
      "Marqueurs colorés",
      "Kit de toilette de voyage",
      "Kettlebell",
      "Sac de voyage à roulettes",
      "Couverture extérieure",
      "Infuseur à thé",
      "Machine à glaçons portable",
      "Prise domotique intelligente",
      "Spiraliseur à légumes",
      "Sous-verres en céramique",
      "Thermomètre à viande numérique",
      "Bloc de yoga",
      "Bol d'eau pliable",
      "Mousqueton",
      "Tapis de puzzle",
      "Balance de bagages",
      "Hamac de camping",
      "Chapeau de soleil pliable",
      "Set de brosses à dents en bambou",
      "Bâton de randonnée",
      "Chauffe-mains",
      "Transmetteur FM Bluetooth",
      "Grill portable au charbon de bois",
      "Sac étanche",
      "Tapis de cuisson en silicone",
      "Sac à linge de voyage",
      "Chauffe-mains rechargeable",
      "Bouteille d'eau pliable",
      "Oreiller de voyage gonflable",
      "Poubelle de voiture",
      "Machine à expresso portable",
      "Organisateur de câbles",
      "Paille en acier inoxydable réutilisable",
      "Réchaud de camping",
      "Sacs de stockage alimentaire en silicone",
      "Dés en fitness",
      "Lampe de livre LED",
      "Saladiers en acier inoxydable",
      "Stickers phosphorescents pour étoiles",
      "Barbecue portable",
      "Portefeuille de cou",
      "Outil polyvalent",
      "Tente de camping",
      "Support pour ordinateur portable réglable",
      "Cube de puzzle",
      "Organisateur de câble magnétique",
      "Masque de sommeil avec bouchons d'oreille",
      "Bandes de résistance en boucle",
      "Contenant alimentaire pliable",
      "Lit de camp",
      "Mini trousse de premiers soins",
      "Lampe frontale de camping",
      "Corde à linge rétractable",
      "Rouleau de mousse",
      "Chargeur solaire pliable",
      "Emballages alimentaires en cire d'abeille réutilisables",
      "Cafetière de camping",
      "Kit de réparation de vélo",
      "Outil multi-usage",
      "Table portable pour l'extérieur",
      "T-shirt basique",
      "Chaussettes en coton",
      "Bouteille d'eau en acier inoxydable",
      "Organisateur de bureau en bois",
      "Lampe de bureau LED",
      "Ensemble de cahiers",
      "Sac à dos en toile",
      "Souris sans fil",
      "Mug de café",
      "Parapluie de poche",
      "Écouteurs Bluetooth",
      "Batterie externe portable",
      "Pichet d'eau en verre",
      "Poêle antiadhésive",
      "Tapis de yoga",
      "Oreiller de voyage",
      "Portefeuille en cuir",
      "Lunettes de soleil",
      "Chaise de bureau",
      "Pot de fleur en céramique",
      "Sac à dos de randonnée",
      "Réveil numérique",
      "Mug de voyage en acier inoxydable",
      "Suivi de fitness",
      "Clé USB",
      "Support pour smartphone",
      "Sac de courses réutilisable",
      "Set de couverts en acier inoxydable",
      "Tapis de souris de jeu",
      "Sèche-cheveux",
      "Set de taies d'oreiller en coton",
      "Set de bandes de résistance",
      "Minuteur de cuisine",
      "Horloge murale",
      "Set de brosses à dents en bambou",
      "Gants de jardinage",
      "Câble HDMI",
      "Tablier de cuisine",
      "Support pour ordinateur portable",
      "Chaussures de course",
      "Chiffons de nettoyage en microfibre",
      "Boîte à lunch isolée",
      "Set de serviettes en coton",
      "Enceinte Bluetooth",
      "Ceinture de course",
      "Masque de sommeil",
      "Tapis de cuisson en silicone",
      "Chargeur sans fil",
      "Saladiers en acier inoxydable",
      "Infuseur à thé",
      "Lacets élastiques pour chaussures",
      "Ventilateur portable",
      "Glaçons réutilisables",
      "Crème solaire",
      "Sac à dos pliable",
      "Support de bouteille d'eau pour vélo",
      "Rouleau de mousse pour fitness",
      "Set de stylos à encre gel",
      "Support de téléphone pour voiture",
      "Gel désinfectant pour les mains",
      "Grains de café gourmet",
      "Bureau d'ordinateur portable réglable",
      "Set d'organisateurs de bureau",
      "Set de pailles en acier inoxydable",
      "Guirlande lumineuse LED",
      "Journal en similicuir",
      "Bouilloire électrique",
      "Kit d'outils de réparation de vélo",
      "Clavier Bluetooth portable",
      "Set de bougies en cire de soja",
      "Set de peinture aquarelle métallique",
      "Mélange de pistes de randonnée",
      "Jeu de société de puzzles",
      "Sac à dos d'hydratation",
      "Tapis de yoga antidérapant",
      "Set de bandes de résistance en boucle",
      "Hub USB-C",
      "Plantes succulentes artificielles",
      "Set de pots à épices en verre",
      "Sacs de rangement alimentaire en silicone réutilisables",
      "Oreiller de voyage gonflable",
      "Set de cuisson de camping",
      "Maniques en coton",
      "Bouteille d'eau pliable",
      "Set de housses alimentaires en silicone",
      "Machine à expresso portable",
      "Plante de bureau miniature",
      "Set de cintres en bois",
      "Set d'huiles essentielles d'aromathérapie",
      "Panier à linge pliable",
      "Gobelet à vin isolé",
      "Set de dessous de verre en céramique",
      "Ventilateur de bureau USB",
      "Set de masques en coton",
    ],
    descriptions: ['Description A', 'Description B', 'Description C', 'Description D', 'Description E'],
    prix: ()=>{
      max= 10000
      min= 1
      randomValue=(Math.random() * (max - min + 1)) + min;
      return randomPrice.toFixed(2)
    },
    catégories: ['Électronique', 'Vêtements', 'Maison et Jardin', 'Jouets', 'Livres'],
    images: ['produitA.jpg', 'produitB.jpg', 'produitC.jpg', 'produitD.jpg', 'produitE.jpg'],
    disponibilité:()=>{
      return Math.random()<0.5;
    },
  },
};
