module.exports = {
  véhicules: [
    {
      type: 'Voiture',
      marque: 'Toyota',
      modèle: 'Camry',
      année: 2022,
      couleur: 'Argent',
      typeCarburant: 'Essence',
      transmission: 'Automatique',
    },
    {
      type: 'Camion',
      marque: 'Ford',
      modèle: 'F-150',
      année: 2023,
      couleur: 'Bleu',
      typeCarburant: 'Diesel',
      transmission: 'Automatique',
    },
    {
      type: 'Moto',
      marque: 'Harley-Davidson',
      modèle: 'Street Glide',
      année: 2021,
      couleur: 'Noir',
      typeCarburant: 'Essence',
      transmission: 'Manuelle',
    },
    {
      type: 'VUS',
      marque: 'Honda',
      modèle: 'CR-V',
      année: 2022,
      couleur: 'Rouge',
      typeCarburant: 'Hybride',
      transmission: 'Automatique',
    },
    {
      type: 'Voiture Électrique',
      marque: 'Tesla',
      modèle: 'Modèle 3',
      année: 2023,
      couleur: 'Blanc',
      typeCarburant: 'Électrique',
      transmission: 'Automatique',
    },
    // Ajoutez plus de véhicules au besoin
  ],
};
